### ISSUE TITLE
Review 24/08

### ISSUE THREAD

**Issue by behemoth-thaodtt** [MinhMonster/demowebsite#1]
- [ ] Em hạn chế dùng div trống nhé (ví dụ như `<div class="main-header"></div>`), thay vào đó có thể css bằng `after` hoặc `before`

Còn lại chị thấy oke rồi đó

**Comment by MinhMonster** [comment]
Dạ vâng, em cảm ơn c ạ! E sẽ cố gắng rút kinh nghiệm cho bài sau ạ!

Thanks!

Đõ Công Minh

Vào Th 4, 24 thg 8, 2022 lúc 15:41 behemoth-thaodtt <
***@***.***> đã viết:
